spring:
  datasource:
    url: jdbc:mysql://10.1.100.20:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath*:/templates/
    check-template: false
    check-template-location: false
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  # 开启缓存
  cache:
    type: jcache # 该属性会自动装配JCacheCacheManager
    jcache:
      config: classpath:/cache/ehcache.xml
  # kafka 配置
  kafka:
    bootstrap-servers: redismaster:9092,redisnode1:9092,redisnode2:9092
    consumer:
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
